CREATE OR REPLACE DATABASE football_data;

CREATE OR REPLACE SCHEMA football_data.raw;

CREATE OR REPLACE WAREHOUSE football_wh
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
